name: stepp 
base: core18 
version: ‘0.1’
summary: Easy SSH management tool with encryption # 79 char long summary
description: 
       you can think of alias for ssh connections with encryption
  

grade: stable
confinement: strict

apps:
    stepp:
     command:executable/main.go
    plugs:
      - home
      - network
      - network-bind
parts:
  cli:
   
    plugin: golang
    source: https://github.com/Gelistiren-Kafalar/step.git
    golang-packages:
    - git
    - go
    - make

