name: stepp 
base: core18 
version: ‘master’
summary: Easy SSH management tool with encryption 
description: 
       you can think of alias for ssh connections with encryption
  

grade: devel
confinement: devmode

apps:
    stepp:
     command:stepp
   
parts:
  stepp:
    plugin: go
    source: https://github.com/Gelistiren-Kafalar/step.git
   

